name: CI
on:
  workflow_dispatch:
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Check for required variables
        run: |
          if [[ -z "${{ secrets.LHCI_TOKEN }}" || -z "${{ vars.LHCI_SERVER_BASE_URL }}" ]]; then
            echo "::error::Lighthouse CI is skipped because LHCI_TOKEN or LHCI_SERVER_BASE_URL is missing."
            exit 1 # Or exit 0 if you want to allow it to pass
          fi
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 2
      - name: run Lighthouse CI
        run: npx @lhci/cli autorun
        env:
          LHCI_TOKEN: ${{ vars.LHCI_TOKEN }}
          LHCI_SERVER_BASE_URL: ${{ vars.LHCI_SERVER_BASE_URL }}
          LHCI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
